### ISSUE TITLE
Inconsistency in definition of theta_d?

### ISSUE THREAD

**Issue by mkae** [jdupuy/dj_brdf#1]
Hi Jonathan,

I've come across a possible problem with the definition of `theta_d`. The code in the repo as well as in Listing 2.2 of your thesis makes clear that `theta_d` is the angle between the outgoing vector and the halfway vector.

But [Rusinkiewicz's paper](https://www.cs.princeton.edu/~smr/papers/brdf_change_of_variables/brdf_change_of_variables.pdf) relates it to the incoming vector, as can be seen in his Figure 2.

Citing page 4, end of last paragraph:

> The two rotations in equation 9 bring the halfangle `h` to the north pole, and (`theta_d` , `phi_d`) are the spherical coordinates of the incident ray in this transformed frame.

I guess his document must be at fault\* and not your thesis, right?! :-)

Greets, Marko

*) perhaps being just a preliminary text and not the finally published version

**Comment by mkae** [comment]
Just seeing on your thesis' page 8 that you use the same definition for `d` as Rusinkiewicz does, i.e. with respect to the incoming vector `i`. Am puzzled now...

**Comment by mkae** [comment]
..., my goodness, now only I realize that the result should be exactly the same, as `dot(i,h) == dot(o,h)`.

Thus, this is only a question of consistency between text and code, no?!

**Comment by jdupuy** [comment]
Hi Marko,
thanks for taking the time to write.
Could you please indicate where the code is inconsistent ? Which lines are you referring to ?
In any case, theta_d does indeed follow the equality cos(theta_d) = dot(h, o) = dot(h, i).
Best,
J

**Comment by mkae** [comment]
I know, this is an extreme form of nitpicking...
Look in line 1535: https://github.com/jdupuy/dj_brdf/blob/master/dj_brdf.h#L1535

**Comment by jdupuy** [comment]
Ok so given that dot(h, i) = dot(h, o), would you agree that this line isn't really an issue (as it still respects the definition of theta_d) ?
EDIT: you can also have a look at Figure 2.1(3) in my thesis for a geometric illustration of the relation between i, o, and h.

**Comment by mkae** [comment]
Yeah, of course!
As I already wrote above: it's a nonsense issue from my side. I was just puzzled by the formula not being identical to the graph.
We can close this! :+1:
