### ISSUE TITLE
Extend to other BRDF data formats?

### ISSUE THREAD

**Issue by mkae** [jdupuy/dj_brdf#2]
I was wondering whether one could easily extend this to other BRDF data file formats.

In my concrete case it looks like one should be able to create a new class `ISSA` which would get a constructor loading data from Radiant's `*.bsdf` file and a BRDF lookup method `ISSA::eval()`, right?

Before I experiment any further with this: Which license has this code?

**Comment by jdupuy** [comment]
The code is public domain.
To get things working quickly, you should indeed implement the `brdf::eval()` function, see, e.g., the merl class. If you know how to importance sample the BRDF, you should also implement the `brdf::sample()` and `brdf::pdf()` functions too. Note that by default, the BRDF is importance sampled according to cos(theta_i).

**Comment by mkae** [comment]
Thanks for the info.
Reading on I notice that Beckmann is not sufficient a model for my use case of broad BRDF profiles with lots of Lambertian-like background...

**Comment by jdupuy** [comment]
If you don't have good importance sampling, you can use the tabular microfacet BRDF sampler (but only for sampling, you must still evaluate with your code). This is what I did for several Mitsuba plugins, and I've found it worked reasonably well. Have a look at the dj_merl plugin in the mitsuba forlder for instance.

**Comment by mkae** [comment]
Well, I am not interested in CG, more in fitting measured data against a reasonable model, you see. Thus I am not using a renderer or anything...
